apiVersion: apps/v1
kind: Deployment
metadata:
  name: "a3-app"
spec:
  selector:
    matchLabels:
      app: "a3"
  replicas: 5
  template:
    metadata:
      labels:
        app: "a3"
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: "a3"
        ports:
        - containerPort: 80

