apiVersion: apps/v1
kind: Deployment
metadata:
  name: "a3-app"
spec:
  selector:
    matchLabels:
      app: "a3"
  replicas: 5
  template:
    metadata:
      labels:
        app: "a3"
    spec:
      containers:
      - image: 424329572650.dkr.ecr.us-east-1.amazonaws.com/app:a8b1f6c814dec5ccaf0c790fabbef29ece7dc126
        imagePullPolicy: Always
        name: "a3"
        ports:
        - containerPort: 80

