apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme"
spec:
  selector:
    matchLabels:
      app: "acme"
  # replicas: "{{ .Values.replicaCount }}"
  replicas: 5
  template:
    metadata:
      labels:
        app: "acme"
    spec:
      containers:
      # - name: "{{ .Chart.Name }}"
      - name: acme
        image: 424329572650.dkr.ecr.us-east-1.amazonaws.com/app:9e9e903e2c100630b0b4e2b5c839a831808c0058 
        env:   
        - name: "DB_HOSTNAME"
          value: acme-db-e2e.cluster-cqlvuoxw9zwh.us-east-1.rds.amazonaws.com
        - name: "DB_USERNAME"
          value: postgres
        - name: "DB_PASSWORD"
          value: password
        - name: "DB_NAME"
          value: servian
        - name: "PORT"
          value: "80"
        imagePullPolicy: IfNotPresent
        name: "acme"
        
