apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme"
spec:
  selector:
    matchLabels:
      app: "acme"
  replicas: "{{ .Values.replicaCount }}"
  template:
    metadata:
      labels:
        app: "acme"
    spec:
      containers:
      - name: "{{ .Chart.name }}"
        image: "{{ .Values.image }}"
        env:   
        - name: "DB_HOSTNAME"
          value: {{ endpoint }}
        - name: "DB_USERNAME"
          value: "{{ .Values.dbUser }}"
        - name: "DB_PASSWORD"
          value: "{{ .Values.dbPass }}"
        - name: "DB_NAME"
          value: "{{ .Values.dbName }}"
        - name: "PORT"
          value: "80"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        name: "acme"
        
