apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme"
spec:
  selector:
    matchLabels:
      app: "acme-app"
  # replicas: "{{ .Values.replicaCount }}"
  replicas: 5
  template:
    metadata:
      labels:
        app: "acme-app"
    spec:
      containers:
      # - name: "{{ .Chart.Name }}"
      - name: acme-app
        image: 424329572650.dkr.ecr.us-east-1.amazonaws.com/app:2c0b2561dfd8aad3b43a26a3ecee0a35b0957a31
        env:
        - name: "NODE_ENV"
          value: prod
        - name: "DB_HOSTNAME"
          value: acme-db-test.cluster-cqlvuoxw9zwh.us-east-1.rds.amazonaws.com
        - name: "DB_USERNAME"
          value: postgres
        - name: "DB_PASSWORD"
          value: password
        - name: "DB_NAME"
          value: servian
        - name: "PORT"
          value: "80"
        imagePullPolicy: IfNotPresent
        name: "acme"
        
